"""The whole of what a flow imports.

A flow is an async function that declares the agents it drives, the environments they work
in and the params it takes, and is handed exactly those::

    from hmz.flows import Agent, AgentCollection, Env, EnvCollection, FlowContext
    from hmz.flows import FlowParams, LocalEnv, ShellEnvMixin, flow


    class Workspace(LocalEnv, ShellEnvMixin): ...


    class Agents(AgentCollection):
        coder: Agent


    class Envs(EnvCollection):
        workspace: Workspace


    class Params(FlowParams):
        rounds: int = 3


    @flow(agents=Agents, envs=Envs, params=Params)
    async def ralph(task, *, agents: Agents, envs: Envs, params: Params, ctx: FlowContext):
        coder, workspace = agents["coder"], envs["workspace"]
        session = await coder.spawn(env=workspace)
        for _ in range(params.rounds):
            await coder.run(task, session=session)

What is here is types: the protocols a flow's agents, environments, sessions and context
answer to (:mod:`~hmz.flows.agents`, :mod:`~hmz.flows.envs`, :mod:`~hmz.flows.defining`),
the moments a hook is hung on (:mod:`~hmz.flows.hooks`), and everything a flow can catch
(:mod:`~hmz.flows.errors`). The objects a flow is handed are the runtime's, and answer to
these structurally. Three things here do run: :func:`flow`, :func:`load` and
`Outworlder.new`, each of which hands its call to :mod:`hmz.runtime.flowing` when it is made
-- so importing this costs pydantic and nothing of humanize's own.
"""

from __future__ import annotations

from .agents import (
    HARNESS_AGENTS,
    Agent,
    AgentCollection,
    AntigravityAgent,
    AskUserHookAgentMixin,
    Budget,
    ClaudeCodeAgent,
    CodexAgent,
    CursorAgent,
    DeepSeekHarnessAgent,
    GoalCommandAgentMixin,
    GrokBuildAgent,
    HarnessKind,
    KimiCodeAgent,
    LoopCommandAgentMixin,
    MiMoCodeAgent,
    OpenCodeAgent,
    Outworlder,
    Permission,
    PermissionKind,
    PermissionRequestHookAgentMixin,
    PiAgent,
    QwenCodeAgent,
    Session,
    SteeringAgentMixin,
    SubagentStartHookAgentMixin,
    SubagentStopHookAgentMixin,
    Usage,
    ZCodeAgent,
)
from .defining import Flow, FlowContext, FlowFn, FlowParams, FlowState, flow, load
from .envs import (
    BashEnvMixin,
    CPUEnvMixin,
    Env,
    EnvBackendKind,
    EnvCollection,
    FilesEnvMixin,
    GitWorktreeEnvMixin,
    GPUEnvMixin,
    LocalEnv,
    MemoryEnvMixin,
    ScratchDirEnvMixin,
    SequenceNotStr,
    ShellEnvMixin,
    TemporaryClonedDirEnvMixin,
)
from .errors import (
    BudgetExceeded,
    CapabilityMissing,
    CapabilityNotGranted,
    CostExceeded,
    DurationExceeded,
    EnvCommandTimeout,
    EnvConnectionError,
    EnvError,
    EnvFileNotFound,
    EnvPermissionDenied,
    EnvUnavailable,
    FlowCancelled,
    FlowDefinitionError,
    FlowDepthExceeded,
    FlowException,
    FlowLoadConflict,
    FlowNotFound,
    FlowRefError,
    FlowRuntimeError,
    HarnessContended,
    HarnessDropped,
    HarnessError,
    HarnessKilled,
    HarnessMismatch,
    HarnessMissing,
    HarnessNotInstalled,
    HarnessRefused,
    HarnessSandboxed,
    HarnessThrottled,
    HarnessUnrecoverable,
    MissingRole,
    ModelUnavailable,
    OutputSchemaError,
    OutputTokensExceeded,
    OutworlderAway,
    ParamsError,
    PermissionTooNarrow,
    RequirementError,
    ResourceUnmet,
    ScratchError,
    SessionError,
    StateNotSerializable,
    TempCloneBusy,
    UnsupportedOperation,
    WorktreeError,
)
from .hooks import (
    HOOK_TYPES,
    AskUserHookParams,
    AskUserHookResult,
    HookFn,
    HookKind,
    HookParams,
    HookResult,
    NotificationHookParams,
    NotificationHookResult,
    OutworlderRunHookParams,
    OutworlderRunHookResult,
    PermissionRequestHookParams,
    PermissionRequestHookResult,
    PreToolUseHookParams,
    PreToolUseHookResult,
    SessionEndHookParams,
    SessionEndHookResult,
    SessionStartHookParams,
    SessionStartHookResult,
    StopHookParams,
    StopHookResult,
    SubagentStartHookParams,
    SubagentStartHookResult,
    SubagentStopHookParams,
    SubagentStopHookResult,
    UserPromptSubmitHookParams,
    UserPromptSubmitHookResult,
)

__all__ = [
    "HARNESS_AGENTS",
    "HOOK_TYPES",
    "Agent",
    "AgentCollection",
    "AntigravityAgent",
    "AskUserHookAgentMixin",
    "AskUserHookParams",
    "AskUserHookResult",
    "BashEnvMixin",
    "Budget",
    "BudgetExceeded",
    "CPUEnvMixin",
    "CapabilityMissing",
    "CapabilityNotGranted",
    "ClaudeCodeAgent",
    "CodexAgent",
    "CostExceeded",
    "CursorAgent",
    "DeepSeekHarnessAgent",
    "DurationExceeded",
    "Env",
    "EnvBackendKind",
    "EnvCollection",
    "EnvCommandTimeout",
    "EnvConnectionError",
    "EnvError",
    "EnvFileNotFound",
    "EnvPermissionDenied",
    "EnvUnavailable",
    "FilesEnvMixin",
    "Flow",
    "FlowCancelled",
    "FlowContext",
    "FlowDefinitionError",
    "FlowDepthExceeded",
    "FlowException",
    "FlowFn",
    "FlowLoadConflict",
    "FlowNotFound",
    "FlowParams",
    "FlowRefError",
    "FlowRuntimeError",
    "FlowState",
    "GPUEnvMixin",
    "GitWorktreeEnvMixin",
    "GoalCommandAgentMixin",
    "GrokBuildAgent",
    "HarnessContended",
    "HarnessDropped",
    "HarnessError",
    "HarnessKilled",
    "HarnessKind",
    "HarnessMismatch",
    "HarnessMissing",
    "HarnessNotInstalled",
    "HarnessRefused",
    "HarnessSandboxed",
    "HarnessThrottled",
    "HarnessUnrecoverable",
    "HookFn",
    "HookKind",
    "HookParams",
    "HookResult",
    "KimiCodeAgent",
    "LocalEnv",
    "LoopCommandAgentMixin",
    "MemoryEnvMixin",
    "MiMoCodeAgent",
    "MissingRole",
    "ModelUnavailable",
    "NotificationHookParams",
    "NotificationHookResult",
    "OpenCodeAgent",
    "OutputSchemaError",
    "OutputTokensExceeded",
    "Outworlder",
    "OutworlderAway",
    "OutworlderRunHookParams",
    "OutworlderRunHookResult",
    "ParamsError",
    "Permission",
    "PermissionKind",
    "PermissionRequestHookAgentMixin",
    "PermissionRequestHookParams",
    "PermissionRequestHookResult",
    "PermissionTooNarrow",
    "PiAgent",
    "PreToolUseHookParams",
    "PreToolUseHookResult",
    "QwenCodeAgent",
    "RequirementError",
    "ResourceUnmet",
    "ScratchDirEnvMixin",
    "ScratchError",
    "SequenceNotStr",
    "Session",
    "SessionEndHookParams",
    "SessionEndHookResult",
    "SessionError",
    "SessionStartHookParams",
    "SessionStartHookResult",
    "ShellEnvMixin",
    "StateNotSerializable",
    "SteeringAgentMixin",
    "StopHookParams",
    "StopHookResult",
    "SubagentStartHookAgentMixin",
    "SubagentStartHookParams",
    "SubagentStartHookResult",
    "SubagentStopHookAgentMixin",
    "SubagentStopHookParams",
    "SubagentStopHookResult",
    "TempCloneBusy",
    "TemporaryClonedDirEnvMixin",
    "UnsupportedOperation",
    "Usage",
    "UserPromptSubmitHookParams",
    "UserPromptSubmitHookResult",
    "WorktreeError",
    "ZCodeAgent",
    "flow",
    "load",
]
